resource "azurerm_service_plan" "main" {
  name                = "plan-${var.prefix}"
  resource_group_name = azurerm_resource_group.main.name
  location            = var.app_service_location
  os_type             = "Linux"
  sku_name            = "B1"
}

resource "azapi_resource" "mcp_server" {
  type      = "Microsoft.Web/sites@2022-03-01"
  name      = "app-${var.prefix}-mcp"
  parent_id = azurerm_resource_group.main.id
  location  = var.app_service_location
  schema_validation_enabled = false

  identity {
    type = "SystemAssigned"
  }

  body = {
    properties = {
      serverFarmId                      = azurerm_service_plan.main.id
      httpsOnly                         = true
      autoGeneratedDomainNameLabelScope = "TenantReuse"
      siteConfig = {
        linuxFxVersion  = "DOTNETCORE|${var.dotnet_version}"
        healthCheckPath = "/health"
        appSettings = [
          { name = "APPINSIGHTS_INSTRUMENTATIONKEY",        value = azurerm_application_insights.main.instrumentation_key },
          { name = "APPLICATIONINSIGHTS_CONNECTION_STRING", value = "@Microsoft.KeyVault(SecretUri=${azurerm_key_vault_secret.app_insights_conn_str.versionless_id})" },
          { name = "EntraId__ClientId",                    value = azuread_application.mcp_server.client_id },
          { name = "EntraId__TenantId",                    value = var.tenant_id },
          { name = "EntraId__ClientSecret",                value = "@Microsoft.KeyVault(SecretUri=${azurerm_key_vault_secret.mcp_client_secret.versionless_id})" },
          { name = "EntraId__Scopes__0",                   value = "api://${azuread_application.mcp_server.client_id}/mcp.access" },
          { name = "EntraId__ResourceDocumentation",       value = "https://github.com/cristofima/dotnet-mcp-server" },
          { name = "DownstreamApi__Audience",              value = "api://${azuread_application.backend_api.client_id}" },
          { name = "DownstreamApi__Scopes__0",             value = "api://${azuread_application.backend_api.client_id}/.default" },
          { name = "DownstreamApi__BaseUrl",               value = "https://${azapi_resource.backend_api.output.properties.defaultHostName}" },
        ]
      }
    }
  }

  response_export_values = ["properties.defaultHostName", "identity"]
}

resource "azapi_resource" "backend_api" {
  type      = "Microsoft.Web/sites@2022-03-01"
  name      = "app-${var.prefix}-api"
  parent_id = azurerm_resource_group.main.id
  location  = var.app_service_location
  schema_validation_enabled = false

  identity {
    type = "SystemAssigned"
  }

  body = {
    properties = {
      serverFarmId                      = azurerm_service_plan.main.id
      httpsOnly                         = true
      autoGeneratedDomainNameLabelScope = "TenantReuse"
      siteConfig = {
        linuxFxVersion  = "DOTNETCORE|${var.dotnet_version}"
        healthCheckPath = "/health"
        appSettings = [
          { name = "APPINSIGHTS_INSTRUMENTATIONKEY",        value = azurerm_application_insights.main.instrumentation_key },
          { name = "APPLICATIONINSIGHTS_CONNECTION_STRING", value = "@Microsoft.KeyVault(SecretUri=${azurerm_key_vault_secret.app_insights_conn_str.versionless_id})" },
          { name = "ConnectionStrings__Default",            value = "@Microsoft.KeyVault(SecretUri=${azurerm_key_vault_secret.backend_api_sql_conn_str.versionless_id})" },
          { name = "EntraId__Audience",                    value = "api://${azuread_application.backend_api.client_id}" },
          { name = "EntraId__TenantId",                    value = var.tenant_id },
        ]
      }
    }
  }

  response_export_values = ["properties.defaultHostName", "identity"]
}

resource "azurerm_role_assignment" "mcp_server_kv" {
  scope                = azurerm_key_vault.main.id
  role_definition_name = "Key Vault Secrets User"
  principal_id         = azapi_resource.mcp_server.output.identity.principalId
}

resource "azurerm_role_assignment" "backend_api_kv" {
  scope                = azurerm_key_vault.main.id
  role_definition_name = "Key Vault Secrets User"
  principal_id         = azapi_resource.backend_api.output.identity.principalId
}
